import JSZip from "jszip";
import { buildNarrative } from "./narrativeBuilder";
import { generateVerumPDF } from "./pdfGenerator";

/*
  MODULE 17 — Disclosure Pack Builder
  -----------------------------------
  • Takes a forensic summary JSON
  • Creates:
      - PDF report
      - Narrative
      - JSON files
      - Cover letter for authority
  • Returns a downloadable ZIP file
*/

export async function buildDisclosurePack(summary, authority = "generic") {

  const zip = new JSZip();

  // 1. Narrative
  const narrative = buildNarrative(summary);
  zip.file("narrative.txt", narrative);

  // 2. PDF
  const pdfBlob = await generateVerumPDF(narrative);
  const pdfArray = await pdfBlob.arrayBuffer();
  zip.file("report.pdf", pdfArray);

  // 3. Forensic Summary JSON
  zip.file("forensic_summary.json", JSON.stringify(summary, null, 2));

  // 4. Chain of Custody
  const chain = {
    generated_at: new Date().toISOString(),
    hash_sha512: await crypto.subtle.digest(
      "SHA-512",
      new TextEncoder().encode(narrative)
    ),
    jurisdiction: summary.jurisdiction ?? "unknown",
    engine_version: "Verum Omnis v5.2.x"
  };
  zip.file("chain_of_custody.json", JSON.stringify(chain, null, 2));

  // 5. Metadata
  const metadata = {
    authority_type: authority,
    note: "This pack was generated by the Verum Omnis Forensic Engine."
  };
  zip.file("metadata.json", JSON.stringify(metadata, null, 2));

  // 6. Cover Letter
  zip.file("authority_cover_letter.txt", generateCoverLetter(authority, summary));

  // Return ZIP
  return await zip.generateAsync({ type: "blob" });
}

function generateCoverLetter(authority, summary) {
  switch (authority) {

    case "saps":
      return `SAPS DISCLOSURE PACK

This pack contains a forensic reconstruction of events, contradictions, risk indicators and behavioural analysis generated by the Verum Omnis Forensic Engine.

The user submits this report under good faith for investigative consideration.

Case summary:
${summary.summary}

This file is sealed using SHA-512 hashing and integrity markers.
`;

    case "uae":
      return `UAE / DUBAI POLICE DISCLOSURE

This pack includes:
• Forensic timeline reconstruction
• Behavioural flags
• Contradictions and metadata discrepancies
• Sealed PDF report

Jurisdiction: UAE

Report is compliant with Verum Omnis v5.2.x integrity rules.
`;

    case "bank":
      return `BANK FRAUD DISCLOSURE PACK

This pack contains:
• Verified forensic report
• Contradiction and fraud markers
• Behavioural indicators
• Evidence chain-of-custody
• SHA-512 verification hash

The user is reporting financial misconduct for urgent review.
`;

    case "court":
      return `COURT DISCLOSURE PACK

This pack contains a sealed forensic account of events and contradictions.

It is suitable for:
• Protection order disputes
• Retaliatory incidents
• Affidavit-style summarisation

Verum Omnis report is stateless and evidence-driven.
`;

    default:
      return `VERUM OMNIS DISCLOSURE PACK

This pack includes:
• Narrative
• Forensic report
• JSON evidence
• Metadata
• Chain-of-custody

Ready for review by the relevant authority.
`;
  }
}
