/*
  MODULE 16: Narrative Builder
  ----------------------------
  Takes:
    - summary JSON
    - contradictions
    - behaviour indicators
    - timeline
    - risk score
  Produces:
    - A structured legal narrative ready for PDF generation
*/

export function buildNarrative(summary) {
  const {
    timeline = [],
    contradictions = [],
    behaviour = [],
    metadataFindings = [],
    riskScore = 0,
    admissions = [],
    summary: textSummary = ""
  } = summary;

  return `
VERUM OMNIS – FORENSIC NARRATIVE REPORT
----------------------------------------

SUMMARY OF EVENTS
${textSummary}

TIMELINE (RECONSTRUCTED)
${timeline.map(t => `• ${t.time} – ${t.event}`).join("\n")}

KEY CONTRADICTIONS
${contradictions.length ? contradictions.map(c => `• ${c.description} (Severity: ${c.severity}/100)`).join("\n") : "None detected"}

BEHAVIOURAL INDICATORS
${behaviour.length ? behaviour.map(b => `• ${b}`).join("\n") : "None detected"}

METADATA ANALYSIS
${metadataFindings.length ? metadataFindings.map(m => `• ${m}`).join("\n") : "No unusual metadata"}

ADMISSIONS / SELF-INCRIMINATING STATEMENTS
${admissions.length ? admissions.map(a => `• ${a}`).join("\n") : "No direct admissions isolated"}

RISK SCORE
${riskScore}/100

INTERPRETATION (HUMAN-READABLE)
• Facts have been reconstructed in chronological order.
• Contradictions and anomalies have been isolated.
• Behavioural signals outline possible deception or coercion.
• This is a forensic interpretation, not legal advice.

NEXT STEPS
• Review evidence
• Determine whether disclosure or reporting is required
• Consider escalating if new contradictions appear

This narrative is auto-generated by the Verum Omnis Forensic Engine.
  `;
}
